# Generated by Django 5.0.2 on 2025-07-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterstics',
            name='category',
            field=models.CharField(choices=[('development', 'Development'), ('marketing', 'Marketing'), ('combo', 'Combo')], default='development', max_length=20),
        ),
        migrations.AlterField(
            model_name='services',
            name='faculty',
            field=models.CharField(choices=[('development', 'Development'), ('digitalmarketing', 'Digital Marketing'), ('combo', 'Combo')], max_length=100),
        ),
        migrations.CreateModel(
            name='ComboService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('development_features', models.ManyToManyField(blank=True, limit_choices_to={'category': 'development'}, related_name='combo_development_features', to='projects.characterstics')),
                ('marketing_features', models.ManyToManyField(blank=True, limit_choices_to={'category': 'marketing'}, related_name='combo_marketing_features', to='projects.characterstics')),
            ],
        ),
    ]
