# Generated by Django 5.0.2 on 2025-07-07 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_characterstics_category_alter_services_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterstics',
            name='category',
        ),
        migrations.DeleteModel(
            name='ComboService',
        ),
    ]
