# Generated by Django 5.0.2 on 2025-07-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('course_type', models.CharField(choices=[('web_development', 'Web Development'), ('digital_marketing', 'Digital Marketing'), ('data_science', 'Data Science & AI'), ('ui_ux', 'UI/UX Design')], max_length=50)),
                ('duration', models.CharField(choices=[('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year')], max_length=20)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], max_length=20)),
                ('batch', models.CharField(choices=[('morning', 'Morning (9 AM - 12 PM)'), ('afternoon', 'Afternoon (2 PM - 5 PM)'), ('evening', 'Evening (6 PM - 9 PM)')], max_length=20)),
                ('qualification', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=150)),
                ('experience', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('expectations', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
