# Generated by Django 5.0.2 on 2025-07-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_courseregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('web_development', 'Web Development'), ('digital_marketing', 'Digital Marketing'), ('data_science', 'Data Science & AI'), ('ui_ux', 'UI/UX Design')], default='web_development', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], default='online', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year')], default='3_months', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels'), ('beginner_to_advanced', 'Beginner to Advanced')], default='beginner', max_length=200),
        ),
    ]
