# Generated by Django 5.0.2 on 2025-07-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_course_type_course_mode_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('online/offline', 'online/offline')], default='online', max_length=200),
        ),
    ]
