# Generated by Django 5.0.2 on 2025-07-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_duration_alter_course_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.JSONField(blank=True, default=list, help_text='Course syllabus stored as JSON'),
        ),
    ]
