# Generated by Django 5.0.2 on 2025-06-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
