# Generated by Django 5.0.2 on 2025-07-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0003_alter_collab_contact_alter_contactus_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab',
            name='contact',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='contact',
            field=models.IntegerField(max_length=20),
        ),
    ]
