# Generated by Django 5.0.2 on 2025-07-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0004_alter_collab_contact_alter_contactus_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(),
        ),
    ]
