# Generated by Django 5.0.2 on 2025-07-09 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254)),
                ('industry_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(100)])),
                ('course_type', models.CharField(choices=[('web_development', 'Web Development'), ('digital_marketing', 'Digital Marketing'), ('data_science', 'Data Science & AI'), ('ui_ux', 'UI/UX Design')], max_length=50)),
                ('duration', models.CharField(choices=[('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year')], max_length=20)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], max_length=20)),
                ('batch', models.CharField(choices=[('morning', 'Morning (9 AM - 12 PM)'), ('afternoon', 'Afternoon (2 PM - 5 PM)'), ('evening', 'Evening (6 PM - 9 PM)')], max_length=20)),
                ('qualification', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=200)),
                ('experience', models.TextField(blank=True)),
                ('skills', models.JSONField(default=list)),
                ('expectations', models.TextField()),
                ('payment_mode', models.CharField(choices=[('full', 'Full Payment'), ('installment', 'Installment')], max_length=20)),
                ('installment_preference', models.CharField(blank=True, choices=[('2_installments', '2 Installments'), ('3_installments', '3 Installments'), ('4_installments', '4 Installments')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('Title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
