# Generated by Django 5.0.2 on 2025-07-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collaboration',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AlterModelOptions(
            name='courseregistration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Course Registration', 'verbose_name_plural': 'Course Registrations'},
        ),
        migrations.RenameField(
            model_name='courseregistration',
            old_name='batch',
            new_name='batch_preference',
        ),
        migrations.RenameField(
            model_name='courseregistration',
            old_name='expectations',
            new_name='course_expectations',
        ),
        migrations.RenameField(
            model_name='courseregistration',
            old_name='experience',
            new_name='relevant_experience',
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='installment_preference',
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='status',
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
