# Generated by Django 5.0.2 on 2025-07-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_collaboration_delete_contact_delete_services_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseRegistration',
        ),
    ]
