# Generated by Django 5.0.2 on 2025-07-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0003_delete_courseregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_type', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='testimonials/logos/')),
                ('quote', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_position', models.CharField(max_length=100)),
                ('author_image', models.ImageField(upload_to='testimonials/authors/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
